当panic异常发生时，程序会中断运行，并立即执行在该goroutine中被延迟的函数（defer 机制）。随后，程序崩溃并输出日志信息。日志信息包括panic value和函数调用的堆栈跟踪信息。

直接调用内置的panic函数也会引发panic异常
panic(fmt.Sprintf("invalid suit %q", s))  


通常情况下，错误的类型是error，它有一个内建的接口。

type error interface {
    Error() string
}

//自定义的出错结构
type myError struct {
    arg  int
    errMsg string
}
//实现Error接口
func (e *myError) Error() string {
    return fmt.Sprintf("%d - %s", e.arg, e.errMsg)
}
